name: CI

on: [push]

jobs:
  build:
    name: Lib workflow
    runs-on: ubuntu-latest

    steps:
      - name: Build lib
        run: >
          curl -H "Accept: application/vnd.github.everest-preview+json"
          -H "Authorization: ${{ secrets.MY_TOKEN }}"
          --request POST
          --data '{"event_type": "lib_updated"}'
          https://api.github.com/repos/geofjamg/test-b/dispatches
