name: CI

on: [push]

jobs:
  build:
    name: Lib workflow
    runs-on: ubuntu-latest

    steps:
      - name: Broadcast event
        uses: gridsuite/broadcast-event@add_orga
        with:
          token: ${{ secrets.MY_TOKEN }}
          event-type: lib_updated
