name: CI

on: [push]

jobs:
  build:
    name: Lib workflow
    runs-on: ubuntu-latest

    steps:
      - name: Broadcast event
        uses: geofjamg/broadcast-event@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: lib_updated
